"""Factory functions for creating Plot widgets."""

import numpy as np
from ..plot import Plot
from .common import _default_color


def plot(
        height=512,
        antialias=3,
        logarithmic_depth_buffer=True,
        background_color=0xffffff,
        camera_auto_fit=True,
        grid_auto_fit=True,
        grid_visible=True,
        screenshot_scale=2.0,
        grid=(-1, -1, -1, 1, 1, 1),
        grid_color=0xe6e6e6,
        label_color=0x444444,
        lighting=1.5,
        menu_visibility=True,
        voxel_paint_color=0,
        colorbar_object_id=-1,
        camera_fov=60.0,
        time=0.0,
        depth_peels=0,
        axes=['x', 'y', 'z'],
        axes_helper=1.0,
        axes_helper_colors=[0xff0000, 0x00ff00, 0x0000ff],
        camera_mode="trackball",
        snapshot_type='full',
        auto_rendering=True,
        camera_no_zoom=False,
        camera_no_rotate=False,
        camera_no_pan=False,
        camera_rotate_speed=1.0,
        camera_zoom_speed=1.2,
        camera_pan_speed=0.3,
        camera_damping_factor=0.0,
        camera_up_axis='none',
        fps=25.0,
        minimum_fps=-1,
        fps_meter=False,
        name=None,
        custom_data=None
):
    return Plot(
        antialias=antialias,
        logarithmic_depth_buffer=logarithmic_depth_buffer,
        background_color=background_color,
        lighting=lighting,
        time=time,
        colorbar_object_id=colorbar_object_id,
        camera_auto_fit=camera_auto_fit,
        grid_auto_fit=grid_auto_fit,
        grid_visible=grid_visible,
        grid_color=grid_color,
        label_color=label_color,
        height=height,
        menu_visibility=menu_visibility,
        voxel_paint_color=voxel_paint_color,
        grid=grid,
        depth_peels=depth_peels,
        axes=axes,
        axes_helper=axes_helper,
        axes_helper_colors=axes_helper_colors,
        screenshot_scale=screenshot_scale,
        camera_fov=camera_fov,
        name=name,
        camera_mode=camera_mode,
        snapshot_type=snapshot_type,
        camera_no_zoom=camera_no_zoom,
        camera_no_rotate=camera_no_rotate,
        camera_no_pan=camera_no_pan,
        camera_rotate_speed=camera_rotate_speed,
        camera_zoom_speed=camera_zoom_speed,
        camera_damping_factor=camera_damping_factor,
        camera_pan_speed=camera_pan_speed,
        camera_up_axis=camera_up_axis,
        auto_rendering=auto_rendering,
        fps=fps,
        minimum_fps=minimum_fps,
        fps_meter=fps_meter,
        custom_data=custom_data
    ) 